services:
  backend:
    build: ./backend
    container_name: chatapp_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: chatapp_frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
